# Generated by Django 4.0 on 2022-01-04 13:20
import datetime

from django.db import migrations


def fill_teachers(apps, schema_editor):
    Teacher = apps.get_model("task1", "Teacher")
    teacher = Teacher(first_name="Ivan", last_name="Ivanov")
    teacher.save()


def fill_students(apps, schema_editor):
    Student = apps.get_model("task1", "Student")
    student = Student(first_name="Petr", last_name="Petrov")
    student.save()


def fill_homeworks(apps, schema_editor):
    Homework = apps.get_model("task1", "Homework")
    Teacher = apps.get_model("task1", "Teacher")
    teacher = Teacher.objects.all()[0]

    dt = datetime.datetime.now()
    delta = datetime.timedelta(days=3) + dt

    dt = dt.strftime('%Y-%m-%d %H:%M:%S')
    delta = delta.strftime('%Y-%m-%d %H:%M:%S')

    hw = Homework(
        text="What is pi?",
        created=dt,
        deadline=delta,
        teacher=teacher)

    hw.save()


def fill_homework_result(apps, schema_editor):
    HomeworkResult = apps.get_model("task1", "HomeworkResult")
    Student = apps.get_model("task1", "Student")
    Homework = apps.get_model("task1", "Homework")

    student = Student.objects.all()[0]
    hw = Homework.objects.all()[0]

    dt = datetime.datetime.now()
    dt = dt.strftime('%Y-%m-%d %H:%M:%S')

    hw_result = HomeworkResult(
        solution="i don't know",
        author=student,
        homework=hw,
        created=dt,
    )
    hw_result.save()


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_teachers),
        migrations.RunPython(fill_students),
        migrations.RunPython(fill_homeworks),
        migrations.RunPython(fill_homework_result),
    ]
